### ISSUE TITLE
`npm audit` issues

### ISSUE THREAD

**Issue by freyamade** [crnbrdrck/Nocturne#36]
There are some Node packages with vulnerabilities.

I tried to upgrade them but it ended up breaking the Amber build.

Can someone better at Node than me pls have a go thank you

**Comment by faustinoaq** [comment]
Hi @crnbrdrck This isssue is fixed here: https://github.com/amberframework/amber/pull/825 :tada:

**Comment by freyamade** [comment]
Awh sweet, thank you so much for the update! :D
